### ISSUE TITLE
How to click on a button or link

### ISSUE THREAD

**Issue by megenov** [gneatgeek/reveal-leap-motion#7]
Hello, 
Can you help me with this. I want to use Leap Motion to clicking over links and buttons. Do you have some simple codes, which I can use for this in reveal. 
Thanks in advance.

**Comment by roryhardy** [comment]
Hi @megenov, 

The plugin will need to be updated with a gesture for clicking. I'm currently planning a re-write of the plugin now that I'm freeing up. I'll try to add a gesture for clicking while I'm at it.  I'll keep this issue open so I can keep you up to date.

In the meantime, I'd recommend only relying on the plugin for navigational and pointing purposes.

**Comment by roryhardy** [comment]
@megenov, I just finished wrapping up v1.0.0! Unfortunately, I probably won't have time to look into this feature for awhile yet.  Would you by chance be interested in giving it a shot?

**Comment by roryhardy** [comment]
@megenov, I've thought about this today and it could probably be solved by pulling the x/y coordinates for the pointer div to locate the link to click on. However, I think a much better solution would be at the OS level by taking control of the mouse altogether. I figured something like this would already exist and it does:

- https://gallery.leapmotion.com/mudra-mouse/
- https://gallery.leapmotion.com/touchless-for-windows/

Hopefully these work for you!
